trigger:
  branches:
    include:
    - master
    - develop
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: vs2017-win2016
  steps:
  - checkout: self
  - task: GoTool@0
    displayName: Use Go 1.10
  - task: Go@0
    displayName: go get
    inputs:
      arguments: -d
  - task: Go@0
    displayName: go build
    inputs:
      command: build
      arguments: -o "$(System.TeamProject).exe"
  - task: ArchiveFiles@2
    displayName: Archive files
    inputs:
      rootFolderOrFile: $(Build.Repository.LocalPath)
      includeRootFolder: False
  - task: PublishBuildArtifacts@1
    displayName: Publish artifact
    condition: succeededOrFailed()
...
