version: '3.8' # 2.4 is the last version that supports depends_on conditions for service health

volumes:
    cassandra-data: {} 

networks:
  cassandra:  # docker network where all cassandra nodes will be put in
  
services:
  cass1:
    image: cassandra:3.11.8   # better to use a specific version, if you want to control upgrades
    container_name: cass1
    hostname: cass1
    mem_limit: 2g  # It's not strictly required, but it's better to have some memory limit
    networks:
      - cassandra
    ports:
      - "9042:9042"  # Expose native binary CQL port for your apps
    volumes:
      - cassandra-data:/var/lib/cassandra
    environment: &environment    # Declare and save environments variables into "environment"
        CASSANDRA_SEEDS: "cass1"    # The first two nodes will be seeds
