version: '3.8' # 2.4 is the last version that supports depends_on conditions for service health

volumes:
    cassandra-data: {} 
    cassandra-post-data: {} 
    cassandra-story-data: {} 


networks:
  cassandra:  # docker network where all cassandra nodes will be put in
  
services:
  cassandra_post:
    image: cassandra:3.11.8   # better to use a specific version, if you want to control upgrades
    container_name: cassandra_post
    mem_limit: 2g  # It's not strictly required, but it's better to have some memory limit
    ports:
      - 7000:9042
    expose: 
      - 7000
    volumes:
      - cassandra-post-data:/var/lib/cassandra
  cassandra_story:
    image: cassandra:3.11.8   # better to use a specific version, if you want to control upgrades
    container_name: cassandra_story
    mem_limit: 2g  # It's not strictly required, but it's better to have some memory limit
    ports:
      - 7001:9042
    volumes:
      - cassandra-story-data:/var/lib/cassandra
    

